# data
data_dir: data/MIMIC-50
data_name: MIMIC-50
min_vocab_freq: 3
max_seq_length: 2500
fixed_length: True
shuffle: True

# train
epochs: 100
batch_size: 16
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 10

# eval
eval_batch_size: 16
monitor_metrics: ['P@1','P@3','P@5']
val_metric: P@5

# model
model_name: XMLCNN
num_filter_per_size: 512 # filter channels
filter_sizes: [4]
num_pool: 2
dropout: 0.2
hidden_dim: 512
dropout2: 0.2
init_weight: kaiming_uniform
activation: relu

# pretrained vocab / embeddings
vocab_file: data/MIMIC-50/vocab.csv
embed_file: data/MIMIC-50/processed_full.embed
