activation: relu
batch_size: 64
config: config/EUR-Lex/kim_cnn_v2_mlce_best.yml
cpu: false
data_dir: /home/eleven/xml-cnn-study-code/data/EUR-Lex
data_name: EUR-Lex
data_workers: 4
display_iter: 100
dropout: 0.2
dropout2: 0.8
embed_cache_dir: /home/eleven/xml-cnn-study-code/.vector_cache
embed_file: glove.6B.300d
epochs: 50
eval: false
eval_batch_size: 256
eval_last: true
filter_sizes:
- 8
fixed_length: false
init_weight: kaiming_uniform
label_file: null
learning_rate: 0.0003
load_checkpoint: null
max_seq_length: 500
metrics_thresholds: 0.5
min_vocab_freq: 1
model_name: KimCNNv2
momentum: 0.9
monitor_metrics:
- P@1
- P@3
- P@5
- nDCG@1
- nDCG@3
- nDCG@5
num_filter_per_size: 768
optimizer: adam
patience: 5
predict_out_path: null
result_dir: /home/eleven/xml-cnn-study-code/runs
search_alg: optuna
seed: 1337
shuffle: true
silent: false
test_path: /home/eleven/xml-cnn-study-code/data/EUR-Lex/test_rv.txt
train_path: /home/eleven/xml-cnn-study-code/data/EUR-Lex/train_rv.txt
use_extended_loss: 1.0
val_metric: P@1
val_path: null
val_size: 0
vocab_file: null
weight_decay: 0
