# data
data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
#fixed_length: True
shuffle: True
train_path: data/EUR-Lex/train_rv.txt
test_path: data/EUR-Lex/test_rv.txt
val_size: 0

# train
seed: 1337
epochs: 50
batch_size: 256
optimizer: adam
learning_rate: 0.0003
weight_decay: 0
patience: 50

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5, nDCG@1, nDCG@3, nDCG@5]
val_metric: P@1

# model
model_name: KimCNNv2
dropout: 0.2
dropout2: 0.4
filter_sizes: [8]
num_filter_per_size: 768 # filter channels
no_transpose: false

# pretrained vocab / embeddings
embed_file: glove.6B.300d
