data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0003
weight_decay: 0
patience: 5
shuffle: true
eval_batch_size: 256
monitor_metrics:
  - P@1
  - P@3
  - P@5
val_metric: P@1
model_name: KimCNNv2
num_filter_per_size: 768
filter_sizes:
  - 8
dropout: 0.2
dropout2: 0.4
init_weight: kaiming_uniform
activation: relu
embed_file: glove.6B.300d
vocab_file: null
search_alg: optuna
embed_cache_dir: .vector_cache
config: config/EUR-Lex/kim_cnn_v2_tune.yml
cpu: false
data_workers: 4
display_iter: 100
eval: false
fixed_length: false
label_file: null
load_checkpoint: null
metrics_thresholds: 0.5
momentum: 0.9
predict_out_path: null
result_dir: runs
silent: false
test_path: data/EUR-Lex/test_rv.txt
train_path: data/EUR-Lex/train_rv.txt
val_path: null
val_size: 0
use_extended_loss: null
eval_last: true
