# data
data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
train_path: data/EUR-Lex/train_rv.txt
test_path: data/EUR-Lex/test_rv.txt
val_path: xdd
val_size: 0

# train
epochs: 50
batch_size: 256
optimizer: adam
learning_rate: 0.0003
weight_decay: 0
patience: 50

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNN
num_filter_per_size: 128 # filter channels
filter_sizes: [2, 4, 8]
num_pool: 2
dropout: 0.25
hidden_dim: 512
dropout2: 0.5
init_weight: kaiming_uniform
activation: relu

# pretrained vocab / embeddings
embed_file: glove.6B.300d
