# data
data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
fixed_length: True

# train
# seed: 1337
epochs: 50
batch_size: 256
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 50

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNNLiu
dropout: 0.25
dropout2: 0.5
conv_stride: 2
filter_sizes: [2, 4, 8]
hidden_dim: 512
max_seq_length: 500
num_filter_per_size: 64 # filter channels
pool_size: 2
no_transpose: true

# pretrained vocab / embeddings
embed_file: glove.6B.300d
