# data
data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500

# train
# seed: 1337
epochs: 100
batch_size: 256
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 50

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNN
dropout: 0.25
dropout2: 0.5
filter_sizes: [2, 4, 8]
hidden_dim: 512
num_filter_per_size: 64 # filter channels
num_pool: 2

# pretrained vocab / embeddings
embed_file: glove.6B.300d
