# data
data_dir: data/AmazonCat-13K
data_name: AmazonCat-13K
min_vocab_freq: 1
max_seq_length: 500
fixed_length: True

# train
#seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0005
weight_decay: 0
patience: 5
shuffle: true

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNNLiu
num_filter_per_size: 32 # filter channels
filter_sizes: [2, 4, 8]
conv_stride: 2
num_pool: 1
pool_size: 2
dropout: 0.2
hidden_dim: 512
dropout2: 0.2

# pretrained vocab / embeddings
embed_file: glove.6B.300d
