# data
data_dir: data/AmazonCat-13K
data_name: AmazonCat-13K
min_vocab_freq: 1
max_seq_length: 500
train_path: data/AmazonCat-13K/train_rv.txt
test_path: data/AmazonCat-13K/test_rv.txt
val_path: xdd
val_size: 0

# train
epochs: 50
batch_size: 256
optimizer: adam
learning_rate: 0.0001
weight_decay: 0
patience: 50

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNN
num_filter_per_size: 768 # filter channels
filter_sizes: [8]
num_pool: 8
dropout: 0.4
hidden_dim: 1024
dropout2: 0.2
init_weight: kaiming_uniform
activation: relu

# pretrained vocab / embeddings
embed_file: glove.6B.300d
