# data
data_dir: data/Amazon-670K
data_name: Amazon-670K
min_vocab_freq: 1
max_seq_length: 500
shuffle: True
train_path: data/Amazon-670K/train_rv.txt
test_path: data/Amazon-670K/test_rv.txt
val_path: null
val_size: 0.2

# train
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 50

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5, nDCG@1, nDCG@3, nDCG@5]
val_metric: P@1

# model
model_name: KimCNNv2
init_weight: kaiming_uniform
dropout: 0.2
dropout2: 0.2
conv_stride: 2
filter_sizes: [8]
num_filter_per_size: 384 # filter channels

# pretrained vocab / embeddings
embed_file: glove.6B.300d
