# data
data_dir: data/Wiki10-31K
data_name: Wiki10-31K
min_vocab_freq: 1
max_seq_length: 500

# train
seed: 1337
epochs: 50
batch_size: 32
optimizer: adam
learning_rate: 0.0005
weight_decay: 0
patience: 5

# eval
eval_batch_size: 32
monitor_metrics: ['P@1','P@3','P@5']
val_metric: P@3

# model
model_name: CAML
num_filter_per_size: 768
filter_sizes: [8]
dropout: 0.2

# pretrained vocab / embeddings
embed_file: glove.6B.300d
