activation: relu
batch_size: 64
config: config/Wiki10-31K/xml_cnn_np8_best.yml
cpu: false
data_dir: data/Wiki10-31K
data_name: Wiki10-31K
data_workers: 4
display_iter: 100
dropout: 0.2
dropout2: 0.4
embed_cache_dir: .vector_cache
embed_file: glove.6B.300d
epochs: 50
eval: false
eval_batch_size: 256
eval_last: true
filter_sizes:
- 8
fixed_length: false
hidden_dim: 1024
init_weight: kaiming_uniform
label_file: null
learning_rate: 0.0003
load_checkpoint: null
max_seq_length: 500
metrics_thresholds: 0.5
min_vocab_freq: 1
model_name: XMLCNN
momentum: 0.9
monitor_metrics:
- P@1
- P@3
- P@5
- nDCG@1
- nDCG@3
- nDCG@5
num_filter_per_size: 384
num_pool: 8
optimizer: adam
patience: 5
predict_out_path: null
result_dir: runs
search_alg: optuna
seed: null
shuffle: true
silent: false
test_path: data/Wiki10-31K/test_rv.txt
train_path: data/Wiki10-31K/train_rv.txt
use_extended_loss: null
val_metric: P@3
val_path: null
val_size: 0
vocab_file: null
weight_decay: 0
